[package]
name = "rust_web"
version = "0.1.0"
edition = "2024"

[dependencies]
num = "0.4.3"
num-rational = "0.4.2"
num-traits = "0.2.19"
quizx = "0.1.0"
serde_json = "1.0.140"
tempfile = "3.20.0"
num-complex = "0.4"
thiserror = "1.0"
serde = "1.0.219"
ordered-float = "5.0.0"
